---
  - name: Installing and Launch Filebeat
    hosts: webservers
    become: yes
    tasks:
      # Use command module
    - name: download filebeat .deb file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.>    # use command module
    - name: install filebeat .deb
      command: dpkg -i filebeat-7.6.1-amd64.deb
    # use copy module
    - name: drop in filebeat.yml
      copy:
        src: /etc/ansible/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml
    # use command module
    - name: enable and configure system module
      command: filebeat modules enable system
    # use command module
    - name: setup filebeat
      command: filebeat setup
    # use command modules
    - name: start filebeat service
      command: service filebeat start

    - name: enable service filebeat on boot
      systemd:
        name: filebeat.service
        enabled: yes